### ISSUE TITLE
Чем я занят Павел

### ISSUE THREAD

**Issue by frolpaxa** [venta-holding/admin#10]
Логи работы

**Comment by frolpaxa** [comment]
23.09.2013
- Выезд в офис "Вента" (Ростовское шоссе, 24), диагностика, ремонт пк (замена блока питания)
- Покупка сетевых фильтров, точки доступа (snr, dns)
- Настройка, установка точки доступа Zyxel Lite 2 в кабинете директора
- Установка, настройка рабочего места (кабинет директора)
- Диагностика неисправности сети 3 этаж (1 розетка), исправление

**Comment by frolpaxa** [comment]
24.09.2013
- Установка MS Office 2013 на пк Малаховой М.
- Покупка переходника микро-HDMI для директора (Красных Партизан 173)
- Удаленная установка Dropbox ИП Родин, ИП Якушев
- Установка MS SQL M STUDIO удаленно 1 пк
- Выезд Аэродромная 33 (забрал оборудование: системный блок, мышка, клавиатура, принтер, монитор, ИБП)
- Выезд Сормовская 105 (Диагностика неисправности ПК, заменил системный блок переставил жесткие диски, активировал лицензию)

**Comment by frolpaxa** [comment]
25.09.2013
- Настройка DHCP сервера (неудача, необходима переустановка, отложил на 7 вечера (т.к. необходима перезагрузка физического сервера) )
- Попытка настройки удаленного доступа к программе Tempo Reale (неудача, т.к. не предусмотрено использование на терминальном сервере)
- Сборка 1 пк из старых комплектующих
- Проверка 2 системных блоков на работоспособность (пойдут на зап.части)
- Подготовка  2 пк в цех (установка: ОС, TV, антивирус, драйвера)

**Comment by frolpaxa** [comment]
26.09.2013
- Восстановление работоспособности DHCP сервера
- Ремонт пк (замена материнской платы, выявил неработоспособный модуль памяти - заменил)
- Подготовка пк для офиса Альфа (Красных Партизан)
  установка: ОС, антивирус, драйвера, WD, TV
- Выезд на Красных Партизан (Альфа), установка рабочего места, настройка пк (сеть, принтер, переставил со старого WI-FI адаптер (внутренний))
- Отвез на красных Партизан (Мир Окон) принтер (не установил, т.к. не хватило USB длины шнура в связи с капризами сотрудницы)
- Проверка б.у. оборудования сортировка непригодных для дальнейшего использования устройств

...(время от времени буду разгребать все б.у. оборудование и сортировать исправное и непригодное для дальнейшего использования)

**Comment by frolpaxa** [comment]
27.09.2013
- Проверка б.у. оборудования сортировка непригодных для дальнейшего использования устройств
  выявил 3 неисправных винчестера, 3 ИБП
- Подготовка пк для офиса на Бабушкина 33
- Выезд на Бабушкина 33 (Установка ПК, провел сеть к пк, настройка сети)
- Выезд в Санрайз (Табрис) покупка USB-удлинителя для Красных Партизан (Мир окон)
- Удаленная настройка Пк на Бабушкина 33 (который отвез)
- Повторный выезд на Бабушкина 33 (передал факс)

**Comment by frolpaxa** [comment]
30.09.2013
- Замена картриджа 3 этаж
- Решение текущих задач
- Поиск, выбор, установка софта для учета пк и оргтехники предприятия (бесплатная, на своем пк)

**\* в 13:00 уехал в институт

**Comment by frolpaxa** [comment]
1.10.2013
- Выезд на северную (Юлмарт), забрал товар, привез в офис
- Поездка на офицерскую за лицензиями Microsoft Windows 7

**\* в 16:00 уехал в институт

**Comment by frolpaxa** [comment]
2.10.2013

**\* в 13:00 приехал с института
- Выезд на Стасова (Юлмарт) забрал товар, привез в офис
- Собрал 5 системных блоков
- Подготовил 3 системных блока (ОС,Драйвера,Софт) 1 из них для фасада

**Comment by frolpaxa** [comment]
03.10.2013
- Переключил ДилОтдел в Cisco
- Подготовил 2 пк (ОС,Драйвера,Софт)
- Внес в базу 13 карточек, завел 1 пользователя, проверил на корректность (проходит идентификацию при отметке на охране)

**\* в 11:00 уехал в институт

**Comment by frolpaxa** [comment]
04.10.2013

**\* приехал в 7:15
- Установил MS Office на новый пк (демо версию)
- Собрал 1 пк для фасада
- Подготовил 2 пк для фасада (ОС,Драйвера,Софт)

**\* в 11:00 уехал в институт

**Comment by frolpaxa** [comment]
7.10.2013

**\* приехал в 7:20
- Заменил блок питания в сис.блоке
- Подготовил пк для цеха (ОС,Драйвера,Софт)
- Поездка на бабушкина (бухгалтерия) за ген. доверенностью
- Поездка в ДНС (Красная) за товаром (ноутбуки, мониторы, мышки, клавиатуры)
- Поездка на бабушкина (бухгалтерия) отвез закрывающие док-ты из ДНС
- Отнес 1 ноутбук, монитор, клавиатуру, мышь на 3 этаж, подключил (Петмансон)

**\* в 13:45 уехал в институт

**Comment by frolpaxa** [comment]
8.10.2013

**\* приехал в 8:40
- Настройка 2 новых ноутбуков (dns)
- Добавил 52 карточки в базу
- Добавил 32 сотрудника
- Заменил сканер (не работал, старый на новый) и память (с 2 на 8 Гб) СГП
- Подготовил пк для Тургенева
- Подготовил ноутбук для менеджера

**\* в 18:15 ЗАКОНЧИЛ РАБОТУ

**Comment by frolpaxa** [comment]
09.10.2013

**\* приехал в 7:15
- Раздал флэш-накопители (usb) ДилОтдел
- Забрал временный пк у менеджера
- Отнес, подключил ноутбук менеджеру (выдал карточку)
- Выезд на Бабушкина 33 (отвез телефонную трубку)
- Выявил неисправность пк СГП (в связи с вирусами, необходима переустановка системы)
- Заменил, настроил пк на СГП
- Провозился с принтером (неудачно) не рабочим принтер оказался

**\* в 14:05 уехал в институт

**Comment by frolpaxa** [comment]
10.10.2013

**\* приехал в 7:20
- Выдаю карточки, добавляю сотрудников
- Подготовил ноутбук для менеджера
- Решил вопрос с картриджами и поломанными принтерами (3 принтера, 1 в ремонт уехал)
- Снял конфиги у пользователей, добавил в программу (ДилОтдел, ТО отдел, IT отдел) для построения списка оборудования на предприятии
- Зарегистрировал учетные записи для Skype (Ростовское шоссе, Луговой проезд, 26/1, Северная, 443 (Корницкого), Северная, 373 (Костылева), Краснодар, улица Бабушкина, 33, Краснодар, улица Красных Партизан, 28, Краснодар, ул. Круговая)
- Отнес и установил на СГП принтер (вероятность повторного сбоя в работе 60%)
- Подготовил пк с СГП (который заменл, т.к. он хорошей комплектации)

**\* в 18:05 ЗАКОНЧИЛ РАБОТУ

**Comment by dnclive** [comment]
образцовый лог!!!

**Comment by frolpaxa** [comment]
10.10.2013

**\* приехал в 8:55
- Установил 1С Директору (Дмитрию Анатольевичу)
- Проверка старых принтеров на работоспособность
- Подготовил пк для цеха (но в нем не рабочая сетевая карта, заменить ее и будет готов)

**\* в 11:00 уехал в институт

**Comment by frolpaxa** [comment]
14.10.2013

**\* приехал в 7:15
- Замена монитора (на новый, Галя)
- Подбор оборудования для предприятия
- Настройка клиента 1С начальнику ДилОтдела
- Установка ПК 1 этаж (старый цех, электрики)
- Решение текущих задач
- Настройка IIS сервера

**Comment by frolpaxa** [comment]
15.10.2013

**\* приехал в 7:15
- Установил адресные классификаторы 1С (доп.версия), сделал копии баз данных
- Составил список ip оборудования, кроме пк (необходимо установить расположения устройств)
- Установка MS_SQL, SQL_EXPRESS, Dropbox диллеру на ноутбук (были проблемы с работой программы, Алексей их решил)
- Решение текущих проблем (смысла описывать все не вижу)

**Comment by frolpaxa** [comment]
- Организовал рабочее место Давиду (переехал с СГП)

**Comment by frolpaxa** [comment]
- Переписал ip-адреса со всех устройств и ПК (составил список)

**Comment by frolpaxa** [comment]
******\* Сколько я намотал киллометров (с 21 октября 2013 года) *******

21.10.2013
- Выезд в dns (Красная ул), отвез документы
- Выезд на Сормовскую (переписал оборудование, заменил ОЗУ с 2 до 4 Гб, Юле)
- Километраж: 28
- Освободился в 18:35

22.10.2013
- Выезд на Красных Партизан "Альфа" (протянул кабель (необходимо спрятать в кабель-канал), перезапустил роутер)
- Километраж: 8

23.10.2013
- Выезд на Красных Партизан "Табрис" (купил 2 USB клавиатуры для Ю.Н. и О.И.)
- Километраж: 7

**Comment by frolpaxa** [comment]
Расходные материалы (мышки):
- на станок (Новый цех)
- Зубенок И.Л.
- Юлия Николаевна
- Павел Фролов

**Comment by frolpaxa** [comment]
- Подготовил ноутбук Юлии Николаевне (подготовил рабочее место (монитор, ноутбук, мышь, клавиатура (временная)))
- Подготовил ноутбук для менеджера
- Подготовил ноутбук Зубенко И.Л.
- Обжал розетку, переключил местами пользователей (розничная сеть)

**Comment by frolpaxa** [comment]
- Поставил принтер, сетевую карту, обновил драйвера электрикам-инженерам (1 этаж, старый цех)
- Провели с Алексеем провод в новый кабинет (старый цех)
- Проложил сеть в новом кабинете (Старый цех)
- Навел порядок на своем рабочем месте и на ремонтном месте
