### ISSUE TITLE
Установка ПК, пакеты программ

### ISSUE THREAD

**Issue by dnclive** [venta-holding/admin#16]
Здесь будем описывать как ставить и что должно быть установлено на компах в зависимости от подразделения

**Comment by dnclive** [comment]
### ПК менеджера

Если переустановка, не забыть сохранить:
- [ ] папку пользователя
- [ ] сохранить базу или проверить чтобы была на D
- [ ] проверить C на пользовательские файлы перенести на D

Установка:
- [ ] сейчас актуально Windows 7 64 бит - борьба с аут оф мемори

#### ставим драйвера
- [ ] материнка
- [ ] принтер, или подключаем сетевой
- [ ] сеть, интернет

#### программы
- [ ] teamviewer
- [ ] dropbox - расшариваем акаунту data и папку менеджера
- [ ] chrome
- [ ] ссылка на кибиком на рабочий стол из (dropbox/data)
- [ ] ярлык ка WD пластик (dropbox/windraw_1.7) ярлык (dropbox/data) - в свойствах объект меняем правильно имя базы и пользователя
- [ ] ярлык ка WD алюминий (dropbox/windraw_alum) ярлык (dropbox/data) - в свойствах объект меняем правильно имя базы и пользователя

#### настройка
- [ ] заходим в WD в Сервис -> настройки и клацаем галочки, выбираем продавца, выгружаем заказ - выбираем путь в dropbox/папка менеджера

**Comment by dnclive** [comment]
## ПК дилера

### Удаленная установка
- [ ] ставим dropbox расшариваем dropbox/diler с admin@venta-holding.ru
- [ ] ставим teamviewer
- [ ] Ждем пока dropbox синхронизирует diler
- [ ] Заходим по teamviewer
- [ ] Ставим сервер
- [ ] Восстанавливаем базу из текущего бекапа в D:/venta/db
- [ ] копируем ярлык из diler проверяем базу и пользователя как при установке менеджеру

## Регистрация в нашей базе
- [ ] создаем продавца (Настройки -> Продавцы) указываем данные все которые дали
- [ ] создаем пользователя (Настройки -> Сотрудники и подразделения) ставит галку Дилеру
- [ ] выгружаем настройки

## Настройка в дилерской базе
- [ ] входим в WD под user 4213, загружаем настройки, проставляем настройки, продавца, выгружаем заказ выбираем папку дилера в dropbox
- [ ] печатаем информацию дилеру

**Comment by dnclive** [comment]
### ПК цех

#### Монитор сборки (готовность)
- [ ] делаем ярлык на рабочий стол из Dropbox\data\windraw_1.7_manuf (или локальной копии этой версии), называем ярлык МОНИТОР
- [ ] добиваем в ярлык в **Объект** через пробелы [название подключения] [пользователь] [пароль] 

пример: **ecad_venta монитор 123**

#### программа для СГП
- [ ]

**Comment by LexXxuS23** [comment]
ПК дилера(подробно)
Этап 1. Подготовка.
объясняем дилеру как скачать teamviewer или ammy admin
Подключаемся.
Ставим dropbox
dils@venta-holding.ru
dils4213
Ждем пока dropbox синхронизируется (по инету от часа, если "наш" LAN - 10 минут).

Этап 2. Установка и проверка
Подключаемся удаленно. Копируем базу и инсталлятор sql из ...Dropbox\diler_inst папку "venta" на диск D (ни в коем случае ничего не распаковываем в dropbox! инсталлировать лучше с диска D)
В зависимости от битности ОС ставим mssql express и sql manager. При установке сервера выбираем смешанный режим и пароль 123123, добавляем группу администраторов, права для запуска служб.
Распаковываем и восстанавливаем в sql manager`e базу ecad_venta из текущего бекапа в D:/venta/db

Пока идет установка подключаемся к главной базе(1.201) windraw под админом.  
Создаем продавца:
Настройки->Продавцы в папке дилер создаем имя продавца по шаблону "ИП Пупкин"
Создаем пользователя:
Настройки->Сотрудники и подразделения:
в папке дилеры создаем пользователя сокращенно "иппуп" или "ипп"(поиском в ФИО смотрим чтобы не было уже %иппуп %ипп)
 в дополнительной строке дублируем пароль
![image](https://f.cloud.github.com/assets/3940122/1332543/d8c7931c-357c-11e3-9cc2-73e15eb50a89.png)
Переходим на вкладку права сотрудников и в папку менеджеры добавляем созданного пользователя
Уточняем у программистов и Ларисы Викторовны можно ли выгружать настройки. Выгружаем настройки полностью(выбираем НЕ для дилера).

На server2 открываем Onenote и создаем отчет-инструкцию для дилера и распечатываем её им.
![image](https://f.cloud.github.com/assets/3940122/1332552/23e60dce-357d-11e3-907f-9ee46662dd05.png)

Выводим ярлыки на рабочий стол из dropbox: папку настройки и Atechnology.winDraw.Main.exe
Запускаем виндроу, настраиваем, заходим для обновления сначала под стандартными паролями.
Подтверждаем обновление скриптов
![image](https://f.cloud.github.com/assets/3940122/1332426/6cd9c5aa-357a-11e3-9243-ed8ea78dc0f7.png)

Полсе обновления в настройках интерфейса ставим галочки везде, выбираем продавца. Под админом добавляем контрагента в папке дилеры с названием как у продавца и дисконтную карту. Скидку которой вам должны были сообщить в тех задании установки программы дилеру(обычно крупный дилер + доставка)

Создаем тестовый заказ и пробуем посчитать любое окно со скидкой и без.

**Comment by LexXxuS23** [comment]
Подключаемся ко всем пк на всех офисах в TW и:

В каждом приемном пункте в 
 ...\Dropbox\data_inst\skype+ammy_adm+hosts
находим всё необходимое для задач ниже

Установить AmmyAdmin службой, добавить в настройках доступа пароль как в teamviewer 42134213

Установка skype
"SkypeSetupFull.exe - Ярлык 7"
или
"Ярлык для SkypeSetupFull.exe для XP"
проверяем запуском и введением учетных данных из таблицы "информ. для it отдела" (в гугл докс, владелец файла LexXxuS)
Для xp sp2 использовать пакет SkypeSetup_6.6.0.106 (1).msi

"Фаервол" - просто подменяем в C:\Windows\System32\drivers\etc файл hosts
если не дает права на вин7 то пуск "notepad" - правой кнопкой - открыть от администратора - далее открываем файл и пересохраняем.
Так же следим чтобы майл сэсурити и прочие антивирусы не стирали изменения в hosts.

Проверить на ломаный софт, особенно winrar и ms ofice. Если всё чисто - создаем админскую учетку "adm"
pass="mpvS4213". Далее на текущую учетку менеджера ставим права "пользователь" и пароль 123. Затем автологин: пуск - выполнить(win+r) -> "control userpasswords2" выделяем учетку юзера и ставим галку(или убираем) чтобы не просил пароль -> применить. Пароль 123. 

После всего ребутнуть и убедиться что всё загружается нормально в автозагрузке. Может слететь dropbox - обратить внимание.
